import { useEffect, useState } from "react";
import AdminLayout from "../components/AdminLayout";
import { useAuth } from "../api/AuthContext";
import { adminApi } from "../api/admin";
import { apiFetch } from "../api/client";
import { toDateInput, formatDateLabel, formatTime, toSlotIsoString } from "../utils/time";
import NoCourse from "../components/NoCourse";

interface Slot {
  id: string;
  startTime: string;
  maxPlayers: number;
  booked: number;
  price: number;
  blocked: boolean;
}

interface ScheduleSettings {
  firstTeeTime: string;
  lastTeeTime: string;
  slotIntervalMinutes: number;
  defaultMaxPlayers: number;
  weekdayPrice: number;
  weekendPrice: number;
  advanceBookingDays: number;
  autoGenerateEnabled: boolean;
}

export default function TeeSheetManager() {
  const { user } = useAuth();
  const [date, setDate] = useState(() => toDateInput(new Date()));
  const [slots, setSlots] = useState<Slot[]>([]);
  const [currencySymbol, setCurrencySymbol] = useState("₹");
  const [loading, setLoading] = useState(true);
  const [newTime, setNewTime] = useState("");
  const [newPrice, setNewPrice] = useState(500);
  const [error, setError] = useState<string | null>(null);
  const [successMsg, setSuccessMsg] = useState<string | null>(null);

  // Schedule & Generator Modal State
  const [showSettingsModal, setShowSettingsModal] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [savingSettings, setSavingSettings] = useState(false);
  const [rangeStartDate, setRangeStartDate] = useState(() => toDateInput(new Date()));
  const [rangeEndDate, setRangeEndDate] = useState(() => {
    const d = new Date();
    d.setDate(d.getDate() + 7);
    return toDateInput(d);
  });

  const [settings, setSettings] = useState<ScheduleSettings>({
    firstTeeTime: "06:00",
    lastTeeTime: "18:00",
    slotIntervalMinutes: 10,
    defaultMaxPlayers: 4,
    weekdayPrice: 500,
    weekendPrice: 750,
    advanceBookingDays: 14,
    autoGenerateEnabled: true,
  });

  async function loadSlots() {
    if (!user?.tenantId) return;
    setLoading(true);
    try {
      const data = await apiFetch<
        { id: string; startTime: string; maxPlayers: number; playersBooked: number; price: number; status: string }[]
      >(`/api/tenants/${user.tenantId}/tee-slots?date=${date}&includeBlocked=true`, {}, user.token, user.tenantId);
      setSlots(
        data.map((s) => ({
          id: s.id,
          startTime: s.startTime,
          maxPlayers: s.maxPlayers,
          booked: s.playersBooked,
          price: s.price,
          blocked: s.status === "blocked",
        }))
      );
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load tee sheet.");
    } finally {
      setLoading(false);
    }
  }

  async function loadScheduleSettings() {
    if (!user?.tenantId) return;
    try {
      const s = await apiFetch<ScheduleSettings>(
        `/api/tenants/${user.tenantId}/schedule-settings`,
        {},
        user.token,
        user.tenantId
      );
      setSettings(s);
      setNewPrice(s.weekdayPrice);
    } catch {
      // default fallback
    }
  }

  useEffect(() => {
    if (user?.tenantId) {
      apiFetch<{ currencySymbol?: string }>(`/api/tenants/${user.tenantId}`, {}, user.token, user.tenantId)
        .then((t) => {
          if (t.currencySymbol) setCurrencySymbol(t.currencySymbol);
        })
        .catch(() => {});
      loadScheduleSettings();
    }
    loadSlots();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user?.tenantId, date]);

  function shiftDate(days: number) {
    const [y, m, d] = date.split("-").map(Number);
    const dt = new Date(y, m - 1, d);
    dt.setDate(dt.getDate() + days);
    setDate(toDateInput(dt));
  }

  async function toggleBlock(id: string, currentlyBlocked: boolean) {
    if (!user?.tenantId) return;
    try {
      await adminApi.setSlotBlocked(user.tenantId, id, !currentlyBlocked, user.token);
      setSlots((prev) => prev.map((s) => (s.id === id ? { ...s, blocked: !currentlyBlocked } : s)));
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to update slot.");
    }
  }

  async function addSlot(e: React.FormEvent) {
    e.preventDefault();
    if (!newTime || !user?.tenantId) return;
    try {
      await apiFetch(
        `/api/tenants/${user.tenantId}/tee-slots`,
        {
          method: "POST",
          body: JSON.stringify({ startTime: toSlotIsoString(date, newTime), maxPlayers: settings.defaultMaxPlayers, price: newPrice }),
        },
        user.token,
        user.tenantId
      );
      setNewTime("");
      await loadSlots();
      setSuccessMsg("Tee slot created successfully.");
      setTimeout(() => setSuccessMsg(null), 3000);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to add slot.");
    }
  }

  // Quick 1-click generation for currently selected day
  async function handleAutoGenerateDay() {
    if (!user?.tenantId) return;
    setGenerating(true);
    setError(null);
    try {
      const res = await apiFetch<{ slotsCreated: number; slotsSkipped: number; message: string }>(
        `/api/tenants/${user.tenantId}/tee-slots/generate-bulk`,
        {
          method: "POST",
          body: JSON.stringify({ startDate: date, endDate: date }),
        },
        user.token,
        user.tenantId
      );
      setSuccessMsg(res.message);
      await loadSlots();
      setTimeout(() => setSuccessMsg(null), 5000);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate slots.");
    } finally {
      setGenerating(false);
    }
  }

  // Bulk generate for custom range
  async function handleGenerateRange(e: React.FormEvent) {
    e.preventDefault();
    if (!user?.tenantId) return;
    setGenerating(true);
    setError(null);
    try {
      const res = await apiFetch<{ slotsCreated: number; slotsSkipped: number; message: string }>(
        `/api/tenants/${user.tenantId}/tee-slots/generate-bulk`,
        {
          method: "POST",
          body: JSON.stringify({
            startDate: rangeStartDate,
            endDate: rangeEndDate,
            firstTeeTime: settings.firstTeeTime,
            lastTeeTime: settings.lastTeeTime,
            slotIntervalMinutes: settings.slotIntervalMinutes,
            defaultMaxPlayers: settings.defaultMaxPlayers,
            weekdayPrice: settings.weekdayPrice,
            weekendPrice: settings.weekendPrice,
          }),
        },
        user.token,
        user.tenantId
      );
      setSuccessMsg(res.message);
      await loadSlots();
      setTimeout(() => setSuccessMsg(null), 6000);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate range.");
    } finally {
      setGenerating(false);
    }
  }

  // Save Schedule Settings
  async function handleSaveScheduleSettings(e: React.FormEvent) {
    e.preventDefault();
    if (!user?.tenantId) return;
    setSavingSettings(true);
    setError(null);
    try {
      const updated = await apiFetch<ScheduleSettings>(
        `/api/tenants/${user.tenantId}/schedule-settings`,
        {
          method: "PUT",
          body: JSON.stringify(settings),
        },
        user.token,
        user.tenantId
      );
      setSettings(updated);
      setSuccessMsg("Operating schedule settings saved successfully.");
      setTimeout(() => setSuccessMsg(null), 4000);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to save schedule settings.");
    } finally {
      setSavingSettings(false);
    }
  }

  if (!user?.tenantId) {
    return (
      <AdminLayout>
        <NoCourse />
      </AdminLayout>
    );
  }

  return (
    <AdminLayout>
      <div className="flex items-center justify-between mb-6 flex-wrap gap-4">
        <div>
          <div className="eyebrow mb-0">Course admin</div>
          <h1 className="text-3xl font-semibold tracking-tight text-fairway">Tee sheet manager</h1>
        </div>

        <div className="flex items-center gap-3 flex-wrap">
          <button
            type="button"
            onClick={() => setShowSettingsModal(true)}
            className="px-3.5 py-2 text-xs font-semibold rounded-xl bg-white border border-sand-dark text-fairway hover:bg-sand-light transition-colors flex items-center gap-1.5 shadow-sm"
          >
            <span>⚙️</span> Schedule & Auto-Generator
          </button>

          <button
            type="button"
            onClick={handleAutoGenerateDay}
            disabled={generating}
            className="px-3.5 py-2 text-xs font-semibold rounded-xl bg-fairway text-white hover:bg-fairway/90 transition-colors flex items-center gap-1.5 shadow-sm disabled:opacity-50"
          >
            <span>⚡</span> {generating ? "Generating..." : `Auto-Generate Day (${formatDateLabel(date)})`}
          </button>
        </div>
      </div>

      {/* Date Navigator Bar */}
      <div className="bg-white rounded-2xl border border-sand-dark p-3.5 mb-6 flex items-center justify-between gap-4 shadow-sm flex-wrap">
        <div className="flex items-center gap-2">
          <button onClick={() => shiftDate(-1)} className="btn-ghost px-3 py-1.5 text-xs font-bold" aria-label="Previous day">← Prev Day</button>
          <div className="flex items-center gap-2">
            <span className="text-sm font-bold text-fairway min-w-[120px] text-center">{formatDateLabel(date)}</span>
            <input
              type="date"
              value={date}
              onChange={(e) => setDate(e.target.value)}
              className="bg-gray-50 border border-gray-200 rounded-xl px-2.5 py-1 text-xs font-semibold text-gray-900 cursor-pointer"
            />
          </div>
          <button onClick={() => shiftDate(1)} className="btn-ghost px-3 py-1.5 text-xs font-bold" aria-label="Next day">Next Day →</button>
        </div>

        <div className="flex items-center gap-2">
          <span className="text-xs text-fairway/60 font-medium">
            Operating: <strong className="text-fairway">{settings.firstTeeTime} – {settings.lastTeeTime}</strong> ({settings.slotIntervalMinutes}m intervals)
          </span>
        </div>
      </div>

      {error && <p className="text-sm text-red-600 bg-red-50 border border-red-200 rounded-xl px-4 py-2.5 mb-4">{error}</p>}
      {successMsg && <p className="text-sm text-green-700 bg-green-50 border border-green-200 rounded-xl px-4 py-2.5 mb-4">✓ {successMsg}</p>}

      {/* Slot Table */}
      <div className="card overflow-hidden mb-8">
        <div className="grid grid-cols-[90px_1fr_100px_90px_100px] text-mono text-xs uppercase tracking-wide text-ink-soft bg-[#FAFBF9] border-b border-[#EEF1ED] px-5 py-3">
          <span>Time</span><span>Booked</span><span>Status</span><span>Price</span><span>Actions</span>
        </div>
        {loading ? (
          <div className="px-5 py-6 space-y-3">
            {Array.from({ length: 4 }).map((_, i) => (
              <div key={i} className="h-4 bg-line rounded animate-pulse" />
            ))}
          </div>
        ) : slots.length === 0 ? (
          <div className="px-5 py-12 text-center">
            <div className="text-3xl mb-2">⛳</div>
            <p className="text-sm font-medium text-ink-soft mb-3">No tee slots generated for {formatDateLabel(date)}.</p>
            <button
              onClick={handleAutoGenerateDay}
              disabled={generating}
              className="px-4 py-2 bg-fairway text-white rounded-xl text-xs font-semibold shadow-sm hover:bg-fairway/90 transition-colors"
            >
              ⚡ Generate Full Day Slots Now
            </button>
          </div>
        ) : (
          slots.map((s) => {
            const full = s.booked >= s.maxPlayers;
            const low = !full && s.booked >= s.maxPlayers - 1 && s.booked > 0;
            const statusLabel = s.blocked ? "Blocked" : full ? "Full" : low ? "Low" : "Open";
            const pillClass = s.blocked ? "pill-red" : full ? "pill-gray" : low ? "pill-gold" : "pill-green";
            return (
              <div key={s.id} className={`grid grid-cols-[90px_1fr_100px_90px_100px] items-center px-5 py-3 border-b border-[#EEF1ED] last:border-b-0 text-sm row-hover ${s.blocked ? "opacity-60" : ""}`}>
                <span className="text-mono font-bold text-gray-900">{formatTime(s.startTime)}</span>
                <span className="text-ink-soft text-xs">{s.booked} / {s.maxPlayers} players</span>
                <span className={`pill w-fit text-xs ${pillClass}`}>{statusLabel}</span>
                <span className="text-mono font-semibold text-gray-900">{currencySymbol}{s.price}</span>
                <button
                  onClick={() => toggleBlock(s.id, s.blocked)}
                  className="text-xs font-semibold text-turf hover:underline text-left"
                >
                  {s.blocked ? "Unblock" : "Block"}
                </button>
              </div>
            );
          })
        )}
      </div>

      {/* Manual Ad-Hoc Slot Adder */}
      <div className="card p-5">
        <h2 className="font-semibold text-fairway text-sm mb-3">➕ Add a single custom tee time — {formatDateLabel(date)}</h2>
        <form onSubmit={addSlot} className="flex gap-3 items-end flex-wrap">
          <div>
            <label className="label">Time</label>
            <input
              type="time"
              required
              value={newTime}
              onChange={(e) => setNewTime(e.target.value)}
              className="border border-line rounded-xl px-3 py-2 text-sm bg-white"
            />
          </div>
          <div>
            <label className="label">Price ({currencySymbol})</label>
            <input
              type="number"
              value={newPrice}
              onChange={(e) => setNewPrice(Number(e.target.value))}
              className="border border-line rounded-xl px-3 py-2 text-sm w-28 font-mono bg-white"
            />
          </div>
          <button type="submit" className="btn-primary rounded-xl px-4 py-2 text-xs">
            Add slot
          </button>
        </form>
      </div>

      {/* Schedule Settings & Bulk Range Generator Modal */}
      {showSettingsModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fadeIn">
          <div className="bg-white rounded-3xl max-w-2xl w-full border border-sand-dark shadow-2xl p-6 sm:p-8 max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between pb-4 border-b border-gray-100 mb-6">
              <div>
                <h3 className="text-xl font-bold text-gray-900">⚙️ Operating Schedule & Automation</h3>
                <p className="text-xs text-gray-500 mt-0.5">Configure course hours, default flight intervals, and auto-generation</p>
              </div>
              <button
                onClick={() => setShowSettingsModal(false)}
                className="w-8 h-8 rounded-full bg-gray-100 hover:bg-gray-200 text-gray-700 flex items-center justify-center text-sm font-bold"
              >
                ✕
              </button>
            </div>

            {/* Section 1: Recurring Operating Schedule */}
            <form onSubmit={handleSaveScheduleSettings} className="space-y-4 mb-8">
              <h4 className="text-xs font-bold uppercase tracking-wider text-fairway">1. Course Schedule Profile</h4>
              
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="label">First Tee Time (Morning)</label>
                  <input
                    type="time"
                    value={settings.firstTeeTime}
                    onChange={(e) => setSettings({ ...settings, firstTeeTime: e.target.value })}
                    className="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm"
                    required
                  />
                </div>

                <div>
                  <label className="label">Last Tee Time (Twilight)</label>
                  <input
                    type="time"
                    value={settings.lastTeeTime}
                    onChange={(e) => setSettings({ ...settings, lastTeeTime: e.target.value })}
                    className="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm"
                    required
                  />
                </div>

                <div>
                  <label className="label">Slot Interval</label>
                  <select
                    value={settings.slotIntervalMinutes}
                    onChange={(e) => setSettings({ ...settings, slotIntervalMinutes: Number(e.target.value) })}
                    className="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm bg-white"
                  >
                    <option value={8}>8 minutes</option>
                    <option value={10}>10 minutes (Standard)</option>
                    <option value={12}>12 minutes</option>
                    <option value={15}>15 minutes</option>
                    <option value={20}>20 minutes</option>
                  </select>
                </div>

                <div>
                  <label className="label">Players Per Flight</label>
                  <input
                    type="number"
                    min={1}
                    max={8}
                    value={settings.defaultMaxPlayers}
                    onChange={(e) => setSettings({ ...settings, defaultMaxPlayers: Number(e.target.value) })}
                    className="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm"
                    required
                  />
                </div>

                <div>
                  <label className="label">Weekday Price ({currencySymbol})</label>
                  <input
                    type="number"
                    min={0}
                    value={settings.weekdayPrice}
                    onChange={(e) => setSettings({ ...settings, weekdayPrice: Number(e.target.value) })}
                    className="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm font-mono"
                    required
                  />
                </div>

                <div>
                  <label className="label">Weekend Price ({currencySymbol})</label>
                  <input
                    type="number"
                    min={0}
                    value={settings.weekendPrice}
                    onChange={(e) => setSettings({ ...settings, weekendPrice: Number(e.target.value) })}
                    className="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm font-mono"
                    required
                  />
                </div>
              </div>

              {/* Automation Toggles */}
              <div className="p-4 rounded-2xl bg-gray-50 border border-gray-200/80 space-y-3">
                <div className="flex items-center justify-between">
                  <div>
                    <span className="text-xs font-bold text-gray-900 block">🌙 Nightly Automated Rollover</span>
                    <span className="text-[11px] text-gray-500">Automatically creates future slots every night in the background</span>
                  </div>
                  <input
                    type="checkbox"
                    checked={settings.autoGenerateEnabled}
                    onChange={(e) => setSettings({ ...settings, autoGenerateEnabled: e.target.checked })}
                    className="w-4 h-4 rounded text-fairway focus:ring-fairway cursor-pointer"
                  />
                </div>

                <div className="flex items-center justify-between pt-2 border-t border-gray-200">
                  <span className="text-xs font-medium text-gray-700">Rolling Horizon (Days in Advance):</span>
                  <input
                    type="number"
                    min={1}
                    max={90}
                    value={settings.advanceBookingDays}
                    onChange={(e) => setSettings({ ...settings, advanceBookingDays: Number(e.target.value) })}
                    className="border border-gray-300 rounded-lg px-2.5 py-1 text-xs w-20 text-center font-bold"
                  />
                </div>
              </div>

              <div className="flex justify-end">
                <button
                  type="submit"
                  disabled={savingSettings}
                  className="px-4 py-2 bg-fairway text-white rounded-xl text-xs font-semibold shadow-sm hover:bg-fairway/90 disabled:opacity-50"
                >
                  {savingSettings ? "Saving Settings..." : "Save Schedule Profile"}
                </button>
              </div>
            </form>

            {/* Section 2: Multi-Day Bulk Generator */}
            <div className="pt-6 border-t border-gray-200">
              <h4 className="text-xs font-bold uppercase tracking-wider text-fairway mb-3">2. Instant Multi-Day Generator</h4>
              <p className="text-xs text-gray-500 mb-4">
                Generate an entire date range immediately using your operating schedule. (Existing booked/created slots will be safely preserved).
              </p>

              <form onSubmit={handleGenerateRange} className="space-y-4">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label className="label">Start Date</label>
                    <input
                      type="date"
                      value={rangeStartDate}
                      onChange={(e) => setRangeStartDate(e.target.value)}
                      className="w-full border border-gray-200 rounded-xl px-3 py-2 text-xs"
                      required
                    />
                  </div>

                  <div>
                    <label className="label">End Date</label>
                    <input
                      type="date"
                      value={rangeEndDate}
                      onChange={(e) => setRangeEndDate(e.target.value)}
                      className="w-full border border-gray-200 rounded-xl px-3 py-2 text-xs"
                      required
                    />
                  </div>
                </div>

                <div className="flex items-center gap-2 flex-wrap">
                  <span className="text-[11px] text-gray-500 font-medium">Quick presets:</span>
                  <button
                    type="button"
                    onClick={() => {
                      const s = toDateInput(new Date());
                      const end = new Date();
                      end.setDate(end.getDate() + 7);
                      setRangeStartDate(s);
                      setRangeEndDate(toDateInput(end));
                    }}
                    className="px-2.5 py-1 text-[11px] font-semibold rounded-lg bg-gray-100 hover:bg-gray-200 text-gray-700"
                  >
                    Next 7 Days
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      const s = toDateInput(new Date());
                      const end = new Date();
                      end.setDate(end.getDate() + 14);
                      setRangeStartDate(s);
                      setRangeEndDate(toDateInput(end));
                    }}
                    className="px-2.5 py-1 text-[11px] font-semibold rounded-lg bg-gray-100 hover:bg-gray-200 text-gray-700"
                  >
                    Next 14 Days
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      const s = toDateInput(new Date());
                      const end = new Date();
                      end.setDate(end.getDate() + 30);
                      setRangeStartDate(s);
                      setRangeEndDate(toDateInput(end));
                    }}
                    className="px-2.5 py-1 text-[11px] font-semibold rounded-lg bg-gray-100 hover:bg-gray-200 text-gray-700"
                  >
                    Next 30 Days
                  </button>
                </div>

                <div className="flex justify-end gap-3 pt-2">
                  <button
                    type="button"
                    onClick={() => setShowSettingsModal(false)}
                    className="px-4 py-2 border border-gray-200 rounded-xl text-xs font-semibold text-gray-700 hover:bg-gray-50"
                  >
                    Close
                  </button>
                  <button
                    type="submit"
                    disabled={generating}
                    className="px-4 py-2 bg-turf text-white rounded-xl text-xs font-semibold shadow-sm hover:bg-turf/90 disabled:opacity-50 flex items-center gap-1.5"
                  >
                    <span>⚡</span> {generating ? "Generating..." : "Generate Date Range Now"}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}
    </AdminLayout>
  );
}
